import Avatar0 from './assets/Avatar0.jpg';
import Avatar1 from './assets/Avatar1.jpg';
import Avatar2 from './assets/Avatar2.jpg';
import Avatar3 from './assets/Avatar3.png';
import Avatar4 from './assets/Avatar4.jpg';

export const data = [
    {
        "id": "0",
        "title": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, culpa vel consectetur molestias, non obcaecati minima quam dicta fugiat quas, consequatur pariatur asperiores possimus quod modi error fuga quae amet facilis eligendi harum totam. Veniam natus facere ex id repellendus?",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia consequuntur reiciendis unde dolore voluptates nobis veniam, rerum et, est, ratione ullam labore suscipit magnam sequi eaque ex quam? Labore possimus assumenda illo, veritatis laudantium itaque voluptatibus molestiae amet quae commodi rerum ad corporis libero fugit deserunt numquam earum quam vero ratione asperiores! Ipsum architecto dolorem consequuntur eos provident dolore modi exercitationem ipsa tempora, explicabo veniam iusto deleniti, nisi natus! Natus tempora nisi cumque explicabo! Vitae enim sed aperiam impedit unde voluptatibus hic alias nam, cumque perferendis rem reiciendis dicta sit necessitatibus quasi tempore, culpa sequi ullam nulla non velit consequatur sint! Aut saepe praesentium suscipit illo inventore cumque consectetur molestiae sapiente iure quo. Deserunt facilis hic ea eum totam unde, temporibus aut modi odit corrupti quos accusantium facere delectus vel eaque quibusdam labore excepturi inventore iure dolore magni perspiciatis quia! Corporis excepturi natus deserunt maxime magnam? Adipisci beatae laboriosam aliquid iusto, quia magni, amet aperiam neque fugiat illo sunt voluptatibus natus? Harum accusantium qui nesciunt et commodi quaerat! Iste quis aperiam neque, repudiandae iure eveniet in ullam saepe voluptate dolores temporibus, possimus quas. Ipsum dolorem at ipsam. Voluptatum quod sint cum inventore adipisci aperiam alias? Reiciendis quae saepe blanditiis?",
        "media": "https://www.oldehansa.ee/wp-content/uploads/2017/09/Merchant-Guild%C2%B4s-Saturday-Feast-1024x683.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "1",
        "title": "Texas slow cooked pulled pork BBQ",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non reiciendis dignissimos sunt iste a officiis eveniet recusandae temporibus repellendus eligendi! Similique, deserunt veritatis nobis magni eos praesentium sequi est exercitationem nihil cum placeat ipsam fugit facere repudiandae maiores repellendus explicabo quaerat mollitia quasi cumque odit modi officiis! Tempora exercitationem alias corporis a doloribus optio odit commodi aliquam cupiditate vitae? Aliquam nihil voluptatibus dolores placeat, eum fugiat ducimus voluptates quae ullam magnam aspernatur atque tenetur. Libero, nihil et modi inventore incidunt ut esse est recusandae culpa voluptatum expedita aliquam voluptatibus nam laborum iusto sequi architecto blanditiis alias aperiam quidem veniam laudantium. Voluptatem quidem quod, alias explicabo deserunt nam ducimus magnam est quae repudiandae. Sint porro, ",
        "media": "https://images.saymedia-content.com/.image/t_share/MTg5MDU4MjM2Njk0MjEwMzc3/medieval-food.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "2",
        "title": "Post three",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://brewminate.com/wp-content/uploads/2018/05/050218-21-Food-Medieval-Middle-Ages.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "3",
        "title": "Post four",
        "category": "Game of Thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/b0/c9/64/b0c964113fa2d77dff565cb3e12d3631.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "4",
        "title": "Post five",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/4c/a2/38/4ca238935fb4575246d3465a3d2f615e.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "5",
        "title": "Post six",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/fe/86/35/fe86351440250894d7f9ec90a25a0939.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "6",
        "title": "Post seven",
        "category": "Game of thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/5d/ee/d7/5deed702ea14d43adfd1213792abcbe6.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "7",
        "title": "Post eight",
        "category": "Harry Potter",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/e9/ac/f3/e9acf30b464d3fdf7a11a615cf530f4a.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },{
        "id": "8",
        "title": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, culpa vel consectetur molestias, non obcaecati minima quam dicta fugiat quas, consequatur pariatur asperiores possimus quod modi error fuga quae amet facilis eligendi harum totam. Veniam natus facere ex id repellendus?",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia consequuntur reiciendis unde dolore voluptates nobis veniam, rerum et, est, ratione ullam labore suscipit magnam sequi eaque ex quam? Labore possimus assumenda illo, veritatis laudantium itaque voluptatibus molestiae amet quae commodi rerum ad corporis libero fugit deserunt numquam earum quam vero ratione asperiores! Ipsum architecto dolorem consequuntur eos provident dolore modi exercitationem ipsa tempora, explicabo veniam iusto deleniti, nisi natus! Natus tempora nisi cumque explicabo! Vitae enim sed aperiam impedit unde voluptatibus hic alias nam, cumque perferendis rem reiciendis dicta sit necessitatibus quasi tempore, culpa sequi ullam nulla non velit consequatur sint! Aut saepe praesentium suscipit illo inventore cumque consectetur molestiae sapiente iure quo. Deserunt facilis hic ea eum totam unde, temporibus aut modi odit corrupti quos accusantium facere delectus vel eaque quibusdam labore excepturi inventore iure dolore magni perspiciatis quia! Corporis excepturi natus deserunt maxime magnam? Adipisci beatae laboriosam aliquid iusto, quia magni, amet aperiam neque fugiat illo sunt voluptatibus natus? Harum accusantium qui nesciunt et commodi quaerat! Iste quis aperiam neque, repudiandae iure eveniet in ullam saepe voluptate dolores temporibus, possimus quas. Ipsum dolorem at ipsam. Voluptatum quod sint cum inventore adipisci aperiam alias? Reiciendis quae saepe blanditiis?",
        "media": "https://www.oldehansa.ee/wp-content/uploads/2017/09/Merchant-Guild%C2%B4s-Saturday-Feast-1024x683.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "9",
        "title": "Post from afar",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non reiciendis dignissimos sunt iste a officiis eveniet recusandae temporibus repellendus eligendi! Similique, deserunt veritatis nobis magni eos praesentium sequi est exercitationem nihil cum placeat ipsam fugit facere repudiandae maiores repellendus explicabo quaerat mollitia quasi cumque odit modi officiis! Tempora exercitationem alias corporis a doloribus optio odit commodi aliquam cupiditate vitae? Aliquam nihil voluptatibus dolores placeat, eum fugiat ducimus voluptates quae ullam magnam aspernatur atque tenetur. Libero, nihil et modi inventore incidunt ut esse est recusandae culpa voluptatum expedita aliquam voluptatibus nam laborum iusto sequi architecto blanditiis alias aperiam quidem veniam laudantium. Voluptatem quidem quod, alias explicabo deserunt nam ducimus magnam est quae repudiandae. Sint porro, ",
        "media": "https://images.saymedia-content.com/.image/t_share/MTg5MDU4MjM2Njk0MjEwMzc3/medieval-food.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "10",
        "title": "Post three",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://brewminate.com/wp-content/uploads/2018/05/050218-21-Food-Medieval-Middle-Ages.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "11",
        "title": "Post four",
        "category": "Game of Thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/b0/c9/64/b0c964113fa2d77dff565cb3e12d3631.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "12",
        "title": "Post five",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/4c/a2/38/4ca238935fb4575246d3465a3d2f615e.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "13",
        "title": "Post six",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/fe/86/35/fe86351440250894d7f9ec90a25a0939.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "14",
        "title": "Post seven",
        "category": "Game of thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/5d/ee/d7/5deed702ea14d43adfd1213792abcbe6.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "15",
        "title": "Post eight",
        "category": "Harry Potter",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/e9/ac/f3/e9acf30b464d3fdf7a11a615cf530f4a.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },{
        "id": "16",
        "title": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, culpa vel consectetur molestias, non obcaecati minima quam dicta fugiat quas, consequatur pariatur asperiores possimus quod modi error fuga quae amet facilis eligendi harum totam. Veniam natus facere ex id repellendus?",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia consequuntur reiciendis unde dolore voluptates nobis veniam, rerum et, est, ratione ullam labore suscipit magnam sequi eaque ex quam? Labore possimus assumenda illo, veritatis laudantium itaque voluptatibus molestiae amet quae commodi rerum ad corporis libero fugit deserunt numquam earum quam vero ratione asperiores! Ipsum architecto dolorem consequuntur eos provident dolore modi exercitationem ipsa tempora, explicabo veniam iusto deleniti, nisi natus! Natus tempora nisi cumque explicabo! Vitae enim sed aperiam impedit unde voluptatibus hic alias nam, cumque perferendis rem reiciendis dicta sit necessitatibus quasi tempore, culpa sequi ullam nulla non velit consequatur sint! Aut saepe praesentium suscipit illo inventore cumque consectetur molestiae sapiente iure quo. Deserunt facilis hic ea eum totam unde, temporibus aut modi odit corrupti quos accusantium facere delectus vel eaque quibusdam labore excepturi inventore iure dolore magni perspiciatis quia! Corporis excepturi natus deserunt maxime magnam? Adipisci beatae laboriosam aliquid iusto, quia magni, amet aperiam neque fugiat illo sunt voluptatibus natus? Harum accusantium qui nesciunt et commodi quaerat! Iste quis aperiam neque, repudiandae iure eveniet in ullam saepe voluptate dolores temporibus, possimus quas. Ipsum dolorem at ipsam. Voluptatum quod sint cum inventore adipisci aperiam alias? Reiciendis quae saepe blanditiis?",
        "media": "https://www.oldehansa.ee/wp-content/uploads/2017/09/Merchant-Guild%C2%B4s-Saturday-Feast-1024x683.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "17",
        "title": "Post from afar",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non reiciendis dignissimos sunt iste a officiis eveniet recusandae temporibus repellendus eligendi! Similique, deserunt veritatis nobis magni eos praesentium sequi est exercitationem nihil cum placeat ipsam fugit facere repudiandae maiores repellendus explicabo quaerat mollitia quasi cumque odit modi officiis! Tempora exercitationem alias corporis a doloribus optio odit commodi aliquam cupiditate vitae? Aliquam nihil voluptatibus dolores placeat, eum fugiat ducimus voluptates quae ullam magnam aspernatur atque tenetur. Libero, nihil et modi inventore incidunt ut esse est recusandae culpa voluptatum expedita aliquam voluptatibus nam laborum iusto sequi architecto blanditiis alias aperiam quidem veniam laudantium. Voluptatem quidem quod, alias explicabo deserunt nam ducimus magnam est quae repudiandae. Sint porro, ",
        "media": "https://images.saymedia-content.com/.image/t_share/MTg5MDU4MjM2Njk0MjEwMzc3/medieval-food.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "18",
        "title": "Post three",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://brewminate.com/wp-content/uploads/2018/05/050218-21-Food-Medieval-Middle-Ages.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "19",
        "title": "Post four",
        "category": "Game of Thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/b0/c9/64/b0c964113fa2d77dff565cb3e12d3631.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "20",
        "title": "Post five",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/4c/a2/38/4ca238935fb4575246d3465a3d2f615e.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "21",
        "title": "Post six",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/fe/86/35/fe86351440250894d7f9ec90a25a0939.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "22",
        "title": "Post seven",
        "category": "Game of thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/5d/ee/d7/5deed702ea14d43adfd1213792abcbe6.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "23",
        "title": "Post eight",
        "category": "Harry Potter",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/e9/ac/f3/e9acf30b464d3fdf7a11a615cf530f4a.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },{
        "id": "24",
        "title": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, culpa vel consectetur molestias, non obcaecati minima quam dicta fugiat quas, consequatur pariatur asperiores possimus quod modi error fuga quae amet facilis eligendi harum totam. Veniam natus facere ex id repellendus?",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia consequuntur reiciendis unde dolore voluptates nobis veniam, rerum et, est, ratione ullam labore suscipit magnam sequi eaque ex quam? Labore possimus assumenda illo, veritatis laudantium itaque voluptatibus molestiae amet quae commodi rerum ad corporis libero fugit deserunt numquam earum quam vero ratione asperiores! Ipsum architecto dolorem consequuntur eos provident dolore modi exercitationem ipsa tempora, explicabo veniam iusto deleniti, nisi natus! Natus tempora nisi cumque explicabo! Vitae enim sed aperiam impedit unde voluptatibus hic alias nam, cumque perferendis rem reiciendis dicta sit necessitatibus quasi tempore, culpa sequi ullam nulla non velit consequatur sint! Aut saepe praesentium suscipit illo inventore cumque consectetur molestiae sapiente iure quo. Deserunt facilis hic ea eum totam unde, temporibus aut modi odit corrupti quos accusantium facere delectus vel eaque quibusdam labore excepturi inventore iure dolore magni perspiciatis quia! Corporis excepturi natus deserunt maxime magnam? Adipisci beatae laboriosam aliquid iusto, quia magni, amet aperiam neque fugiat illo sunt voluptatibus natus? Harum accusantium qui nesciunt et commodi quaerat! Iste quis aperiam neque, repudiandae iure eveniet in ullam saepe voluptate dolores temporibus, possimus quas. Ipsum dolorem at ipsam. Voluptatum quod sint cum inventore adipisci aperiam alias? Reiciendis quae saepe blanditiis?",
        "media": "https://www.oldehansa.ee/wp-content/uploads/2017/09/Merchant-Guild%C2%B4s-Saturday-Feast-1024x683.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "25",
        "title": "Post from afar",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non reiciendis dignissimos sunt iste a officiis eveniet recusandae temporibus repellendus eligendi! Similique, deserunt veritatis nobis magni eos praesentium sequi est exercitationem nihil cum placeat ipsam fugit facere repudiandae maiores repellendus explicabo quaerat mollitia quasi cumque odit modi officiis! Tempora exercitationem alias corporis a doloribus optio odit commodi aliquam cupiditate vitae? Aliquam nihil voluptatibus dolores placeat, eum fugiat ducimus voluptates quae ullam magnam aspernatur atque tenetur. Libero, nihil et modi inventore incidunt ut esse est recusandae culpa voluptatum expedita aliquam voluptatibus nam laborum iusto sequi architecto blanditiis alias aperiam quidem veniam laudantium. Voluptatem quidem quod, alias explicabo deserunt nam ducimus magnam est quae repudiandae. Sint porro, ",
        "media": "https://images.saymedia-content.com/.image/t_share/MTg5MDU4MjM2Njk0MjEwMzc3/medieval-food.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "26",
        "title": "Post three",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://brewminate.com/wp-content/uploads/2018/05/050218-21-Food-Medieval-Middle-Ages.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "27",
        "title": "Post four",
        "category": "Game of Thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/b0/c9/64/b0c964113fa2d77dff565cb3e12d3631.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "28",
        "title": "Post five",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/4c/a2/38/4ca238935fb4575246d3465a3d2f615e.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "29",
        "title": "Post six",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/fe/86/35/fe86351440250894d7f9ec90a25a0939.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "30",
        "title": "Post seven",
        "category": "Game of thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/5d/ee/d7/5deed702ea14d43adfd1213792abcbe6.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "31",
        "title": "Post eight",
        "category": "Harry Potter",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/originals/e9/ac/f3/e9acf30b464d3fdf7a11a615cf530f4a.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },{
        "id": "32",
        "title": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, culpa vel consectetur molestias, non obcaecati minima quam dicta fugiat quas, consequatur pariatur asperiores possimus quod modi error fuga quae amet facilis eligendi harum totam. Veniam natus facere ex id repellendus?",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia consequuntur reiciendis unde dolore voluptates nobis veniam, rerum et, est, ratione ullam labore suscipit magnam sequi eaque ex quam? Labore possimus assumenda illo, veritatis laudantium itaque voluptatibus molestiae amet quae commodi rerum ad corporis libero fugit deserunt numquam earum quam vero ratione asperiores! Ipsum architecto dolorem consequuntur eos provident dolore modi exercitationem ipsa tempora, explicabo veniam iusto deleniti, nisi natus! Natus tempora nisi cumque explicabo! Vitae enim sed aperiam impedit unde voluptatibus hic alias nam, cumque perferendis rem reiciendis dicta sit necessitatibus quasi tempore, culpa sequi ullam nulla non velit consequatur sint! Aut saepe praesentium suscipit illo inventore cumque consectetur molestiae sapiente iure quo. Deserunt facilis hic ea eum totam unde, temporibus aut modi odit corrupti quos accusantium facere delectus vel eaque quibusdam labore excepturi inventore iure dolore magni perspiciatis quia! Corporis excepturi natus deserunt maxime magnam? Adipisci beatae laboriosam aliquid iusto, quia magni, amet aperiam neque fugiat illo sunt voluptatibus natus? Harum accusantium qui nesciunt et commodi quaerat! Iste quis aperiam neque, repudiandae iure eveniet in ullam saepe voluptate dolores temporibus, possimus quas. Ipsum dolorem at ipsam. Voluptatum quod sint cum inventore adipisci aperiam alias? Reiciendis quae saepe blanditiis?",
        "media": "https://www.oldehansa.ee/wp-content/uploads/2017/09/Merchant-Guild%C2%B4s-Saturday-Feast-1024x683.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "33",
        "title": "Post from afar",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non reiciendis dignissimos sunt iste a officiis eveniet recusandae temporibus repellendus eligendi! Similique, deserunt veritatis nobis magni eos praesentium sequi est exercitationem nihil cum placeat ipsam fugit facere repudiandae maiores repellendus explicabo quaerat mollitia quasi cumque odit modi officiis! Tempora exercitationem alias corporis a doloribus optio odit commodi aliquam cupiditate vitae? Aliquam nihil voluptatibus dolores placeat, eum fugiat ducimus voluptates quae ullam magnam aspernatur atque tenetur. Libero, nihil et modi inventore incidunt ut esse est recusandae culpa voluptatum expedita aliquam voluptatibus nam laborum iusto sequi architecto blanditiis alias aperiam quidem veniam laudantium. Voluptatem quidem quod, alias explicabo deserunt nam ducimus magnam est quae repudiandae. Sint porro, ",
        "media": "https://images.saymedia-content.com/.image/t_share/MTg5MDU4MjM2Njk0MjEwMzc3/medieval-food.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "34",
        "title": "Post three",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://brewminate.com/wp-content/uploads/2018/05/050218-21-Food-Medieval-Middle-Ages.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "35",
        "title": "Post four",
        "category": "Game of Thrones",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/b0/c9/64/b0c964113fa2d77dff565cb3e12d3631.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
    {
        "id": "36",
        "title": "Post five",
        "category": "Historical",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "description": "Kale and Quinoa Salad with Black Beans: Vibrant green kale is massaged with a lemony, cumin and chile dressing and tossed with chilled quinoa and black beans for a zesty quinoa salad. ",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://i.pinimg.com/736x/4c/a2/38/4ca238935fb4575246d3465a3d2f615e.jpg",
        "ingredients": [
            "1/2 pound chicken, I used a combo of red and white quinoa, rinsed very well",
            "1 can Olives",
            "2 cups vegetable broth",
            "2 cloves garlic, minced",
            "1/4 cup freshly squeezed lemon or lime juice",
            "3 teaspoons chia seeds",
            "1 avocado, sliced or cubed",
            "1/2 cup grated carrot",
            "1/2 tablespoon cumin",
        ],
        "instructions": [
            "Heat a saucepan. Add the rinsed and drained quinoa and the garlic and toast it until almost dry. Add the vegetable broth, bring to a boil, reduce heat, and cover. Simmer until all the water is absorbed, about 20 minutes. Remove from heat and allow to cool.",
            "While the quinoa is cooking, make the dressing in a small bowl or measuring cup: whisk together the lemon juice, 3 tablespoons broth, chia/flax seeds, chile powders, cumin, and salt. Allow to stand until the chia seeds start to thicken the dressing.",
            "Place the kale in a large serving bowl. Add half of the dressing and massage it into the kale using a wringing motion until the kale is very tender. Two minutes of massaging should do it, but the longer, the better. Add the quinoa, black beans, carrot, and bell pepper, along with the remaining dressing. Mix well and refrigerate until ready to serve.",
            "Just before serving, check the seasoning and add more lemon juice, chile powder, cumin, and salt, as needed. Stir in chopped avocado, if desired, or serve with slices of avocado on the side.",
        ]
    },
];

export const authorDummyData = [
    {id: 0, avatar: Avatar0, name: 'Ernest Achiever', posts: 7},
    {id: 1, avatar: Avatar1, name: 'Ernest Achiever', posts: 2},
    {id: 2, avatar: Avatar2, name: 'Ernest Achiever', posts: 4},
    {id: 3, avatar: Avatar3, name: 'Ernest Achiever', posts: 26},
    {id: 4, avatar: Avatar4, name: 'Ernest Achiever', posts: 3},
];

export default data;