export const data = [
    {
        "id": "0",
        "title": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, culpa vel consectetur molestias, non obcaecati minima quam dicta fugiat quas, consequatur pariatur asperiores possimus quod modi error fuga quae amet facilis eligendi harum totam. Veniam natus facere ex id repellendus?",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia consequuntur reiciendis unde dolore voluptates nobis veniam, rerum et, est, ratione ullam labore suscipit magnam sequi eaque ex quam? Labore possimus assumenda illo, veritatis laudantium itaque voluptatibus molestiae amet quae commodi rerum ad corporis libero fugit deserunt numquam earum quam vero ratione asperiores! Ipsum architecto dolorem consequuntur eos provident dolore modi exercitationem ipsa tempora, explicabo veniam iusto deleniti, nisi natus! Natus tempora nisi cumque explicabo! Vitae enim sed aperiam impedit unde voluptatibus hic alias nam, cumque perferendis rem reiciendis dicta sit necessitatibus quasi tempore, culpa sequi ullam nulla non velit consequatur sint! Aut saepe praesentium suscipit illo inventore cumque consectetur molestiae sapiente iure quo. Deserunt facilis hic ea eum totam unde, temporibus aut modi odit corrupti quos accusantium facere delectus vel eaque quibusdam labore excepturi inventore iure dolore magni perspiciatis quia! Corporis excepturi natus deserunt maxime magnam? Adipisci beatae laboriosam aliquid iusto, quia magni, amet aperiam neque fugiat illo sunt voluptatibus natus? Harum accusantium qui nesciunt et commodi quaerat! Iste quis aperiam neque, repudiandae iure eveniet in ullam saepe voluptate dolores temporibus, possimus quas. Ipsum dolorem at ipsam. Voluptatum quod sint cum inventore adipisci aperiam alias? Reiciendis quae saepe blanditiis?",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    },
    {
        "id": "1",
        "title": "Post from afar",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    },
    {
        "id": "2",
        "title": "Post from afar",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    },
    {
        "id": "3",
        "title": "Post from afar",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    },
    {
        "id": "4",
        "title": "Post from afar",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    },
    {
        "id": "5",
        "title": "Post from afar",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    },
    {
        "id": "6",
        "title": "Post from afar",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    },
    {
        "id": "7",
        "title": "Post from afar",
        "category": "Lord of the Rings",
        "date_posted": "2024-04-05T00:17:53.670Z",
        "prep_time_mins": 9,
        "cook_time_mins": 7,
        "servings": 3,
        "author": "Three Sheets",
        "body": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor necessitatibus qui minima ea atque animi provident quam debitis aut excepturi.",
        "media": "https://imgs.search.brave.com/jfrbNN6Tq0EP3duoRc6QSw3T4txMk_cy79TX_CFyQIQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/YnJpdGFubmljYS5j/b20vMTUvMTgwMDE1/LTEzOC1FRjkxOURF/RS9odW1hbi1oYWly/LmpwZz93PTgwMCZo/PTQ1MCZjPWNyb3A",
    }
]

export default data;